# main branch workflow
name: Pricewagon-Day-Price-Crawling

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # 파이썬 설정
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Execute SSH command on remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            if [ ! -d "$HOME/app/musinsa-pricewagon" ]; then
              git clone https://github.com/MusinsaWagon/crawling.git $HOME/app/musinsa-pricewagon
            else
              cd $HOME/app/musinsa-pricewagon
              git pull
            fi
            cd $HOME/app/musinsa-pricewagon

            touch .env.prod
            echo "${{ secrets.ENV_PROD }}" >> .env.prod

            touch .env
            echo "${{ secrets.ENV }}" >> .env
            echo "${{ secrets.ENV_PROD }}" >> .env

            sudo -S docker rm day-price-container --force  <<< "${{ secrets.SUDO_PASSWORD }}"
            sudo -S docker build -t rong5026/musinsa-pricewagon . <<< "${{ secrets.SUDO_PASSWORD }}"
            sudo -S docker run -d --name day-price-container -v $HOME/app/musinsa-pricewagon/log:/app/log --env-file=.env rong5026/musinsa-pricewagon <<< "${{ secrets.SUDO_PASSWORD }}"
